2024-01-16 14:54:36,267 ERROR: Exception on /api/users/1/post [GET] [in /Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/app/api/users.py", line 89, in get_post
    return User.to_collection_dict(sa.select(Post).where(Post.user_id==id), page, per_page,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/app/models.py", line 82, in to_collection_dict
    'items': [item.to_dict_post() for item in resources.items],
              ^^^^^^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'to_dict_post'
2024-01-16 14:55:39,591 INFO: Microblog startup [in /Users/thanhvy/Documents/microblog/app/__init__.py:90]
2024-01-16 15:08:13,103 INFO: Microblog startup [in /Users/thanhvy/Documents/microblog/app/__init__.py:90]
2024-01-16 15:08:28,371 ERROR: Exception on /api/users/1/post [GET] [in /Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/app/api/users.py", line 88, in get_post
    return Post.to_collection_dict(sa.select(Post).where(Post.user_id==id), page, per_page,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/app/models.py", line 82, in to_collection_dict
    'items': [item.to_dict_post() for item in resources.items],
              ^^^^^^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'to_dict_post'
2024-01-16 15:09:34,688 INFO: Microblog startup [in /Users/thanhvy/Documents/microblog/app/__init__.py:90]
2024-01-16 15:09:45,928 ERROR: Exception on /api/users/3/posts [GET] [in /Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/venv/lib/python3.12/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/app/api/users.py", line 95, in get_all_posts
    return Post.to_collection_dict(sa.select(Post), page, per_page,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thanhvy/Documents/microblog/app/models.py", line 82, in to_collection_dict
    'items': [item.to_dict_post() for item in resources.items],
              ^^^^^^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'to_dict_post'
2024-01-16 15:10:08,651 INFO: Microblog startup [in /Users/thanhvy/Documents/microblog/app/__init__.py:90]
2024-01-16 15:32:43,916 INFO: Microblog startup [in /Users/thanhvy/Documents/microblog/app/__init__.py:90]
2024-01-16 15:46:15,994 INFO: Microblog startup [in /Users/thanhvy/Documents/microblog/app/__init__.py:90]
2024-01-16 15:48:01,310 INFO: Microblog startup [in /Users/thanhvy/Documents/microblog/app/__init__.py:90]
